### ISSUE TITLE
feature : Responsive landing page for the website from the Figma Design

### ISSUE THREAD

**Issue by vedanthv** [Tech-Matrix/PRNTRS#1]
**Is your feature request related to a problem? Please describe.**
There is a Figma Landing Page design but it hasn't been designed with HTML and CSS. **I would like to be assigned the issue** to implement the designs with CSS and Flexbox.

**Describe the solution you'd like**
Design a aesthetic landing page with HTML, CSS, Flexbox and Grid identical to the Figma designs.
 
**Describe alternatives you've considered**
There are no alternatives needed. I can think of implementing in TailwindCSS later on.

**Comment by vedanthv** [comment]
@A-HK @charvibannur I would like to be assigned to the issue

**Comment by vedanthv** [comment]
@A-HK The font in the Figma design is `Segoe Print Bold` but it's not a free font. Can you give me a Google Fonts embed for this font? 
Alternatively I can proceed with using `Kaushan Script` cursive which is strikingly similar to Segoe if that's fine

**Comment by A-HK** [comment]
Sure ! Kaushan Script looks good too; you can use that instead.

**Comment by vedanthv** [comment]
> Sure ! Kaushan Script looks good too; you can use that instead.

Cool. Thanks for the quick response.

**Comment by vedanthv** [comment]
@A-HK should I create another issue for styling? It's better to keep one issue I guess

**Comment by A-HK** [comment]
Reopened the issue now. You can reference the same issue in your styling PR
