### ISSUE TITLE
Improving UI and Front end of client sign in page 

### ISSUE THREAD

**Issue by goel-vanshika** [Tech-Matrix/PRNTRS#10]
improving ui and front end of client sign in page

**Comment by A-HK** [comment]
Hey @goel-vanshika ! This is actually closely related to another issue
Can you please submit a different issue?

**Comment by A-HK** [comment]
Closing this issue for now

**Comment by vedanthv** [comment]
@goel-vanshika you can work on #6 . It's the same issue for improving UI previously assigned to me but you can take it up
