### ISSUE TITLE
Designing the Vendor's details form page

### ISSUE THREAD

**Issue by kruthi3012** [Tech-Matrix/PRNTRS#11]
**Is your feature request related to a problem? Please describe.**
The project currently doesn't have a working Vendor's details form page.

**Describe the solution you'd like**
By referring to the Figma prototype form created by the team, I'd like to convert it into a webpage.

**Additional context**
Add any other context or screenshots about the feature request here
![PRNTRS Vendor Form Details](https://user-images.githubusercontent.com/79209073/133647558-a14c4cf4-b5c7-409c-8ea4-86d63833fa3e.png)
.

**Comment by kruthi3012** [comment]
@A-HK Can you please assign me to this?

**Comment by A-HK** [comment]
Sure thing ! Assigning you here @kruthi3012

**Comment by vedanthv** [comment]
@kruthi3012 Hey Kruthi, can you give all the `<input>` tags a `name` attribute. This would help me a ton because I want to build the backend for the registration form!

**Comment by kruthi3012** [comment]
> @kruthi3012 Hey Kruthi, can you give all the `<input>` tags a `name` attribute. This would help me a ton because I want to build the backend for the registration form!

Yes, sure thing!
