### ISSUE TITLE
feature : Progressive Client Registration Form - Frontend

### ISSUE THREAD

**Issue by vedanthv** [Tech-Matrix/PRNTRS#12]
**Is your feature request related to a problem? Please describe.**

Currently there is no Client Registration Form and I would like to design and implement one with an innovative design. 

**Describe the solution you'd like**

Usually Google Forms is long and it's very long in nature. It would deviate the users attention. I would like to implement a form like **Typeform** which is progressive in nature and the user's attention doesn't deviate.

**Describe alternatives you've considered**

I have a clear plan in mind as of now and don't need to consider alternate solutions.

**Additional context**

I will add screenshots and live demo in my further PR's.

**Comment by A-HK** [comment]
Hey @vedanthv , this sounds cool !

Please send out the design of this dynamic form here before actually working on developing the page.

**Comment by vedanthv** [comment]
> Hey @vedanthv , this sounds cool !
> 
> Please send out the design of this dynamic form here before actually working on developing the page.

I'm not sure that I can send the figma designs. I don't know Figma. Ill send a codepen link instead.

**Comment by vedanthv** [comment]
Please assign me this issue once #13 has been reviewed

**Comment by vedanthv** [comment]
@A-HK Here is the design. I could not come up with a suitable color for the background. As of now its `light red`. Let me know if there is a better color.
![image](https://user-images.githubusercontent.com/44313631/133869642-502b7168-1a94-4151-b669-aa9d541ef3f3.png)

Clicking on the arrow would go to the next question. And not answering the question would give red border to text and a shake to placeholder. Since the JS ain't ready I can't show it here.

**Comment by A-HK** [comment]
Hey @vedanthv , this looks extremely clean !
Great design, and great colours.
You can go right ahead

**Comment by vedanthv** [comment]
> Hey @vedanthv , this looks extremely clean !
> Great design, and great colours.
> You can go right ahead

Alright. Thanks @A-HK

**Comment by vedanthv** [comment]
@A-HK You can leave this issue open because #27  also is regarding this

**Comment by A-HK** [comment]
Hey, yes, that's alright!
I'm sure you know this already, but if the keyword `fixes` is mentioned in the PR followed by the issue number, GitHub automatically links the issue to the PR and closes it.
I'm about to check your 2/2 PR soon, so it'll be fine.

Also, I'm a little confused now. Did you mean #28, or actually #27?

**Comment by vedanthv** [comment]
> Hey, yes, that's alright!
> I'm sure you know this already, but if the keyword `fixes` is mentioned in the PR followed by the issue number, GitHub automatically links the issue to the PR and closes it.
> I'm about to check your 2/2 PR soon, so it'll be fine.

@A-HK Oh okay. In most other repositories, `partially fixes` or `fixes partially`doesn't auto close the issue. I thought its the same here.
