### ISSUE TITLE
feature : Payment Gateway Integration for the Client

### ISSUE THREAD

**Issue by vedanthv** [Tech-Matrix/PRNTRS#26]
**Is your feature request related to a problem? Please describe.**

Currently there is no Payment Gateway Checkout which means client can't pay the vendor. I would like to implement this using Razorpay.

**Describe the solution you'd like**

I am going to using the Razorpay NodeJS SDK, OrdersAPI and their Signature Verification functions to implement this.

**Describe alternatives you've considered**

No alternative solutions thought of so far.

**Additional context**

No additional context as such.

**Comment by vedanthv** [comment]
@A-HK I would like to work on this after the other issues are done and implmented!

**Comment by A-HK** [comment]
Hey @vedanthv , sure, this is a great idea!
You have 3 other issues open though - #16, #14, #12 so I would get to implementing those first obviously xD

**Comment by vedanthv** [comment]
> Hey @vedanthv , sure, this is a great idea!
> You have 3 other issues open though - #16, #14, #12 so I would get to implementing those first obviously xD

Okay. The order I have thought of is #12,#16,#26,#14 @A-HK
