### ISSUE TITLE
minor styling update needed : The styling of Client-Sign-In does not match with other pages

### ISSUE THREAD

**Issue by vedanthv** [Tech-Matrix/PRNTRS#6]
**Is your feature request related to a problem? Please describe.**
This is a minor but important issue. The styling of buttons and placeholders in the Client Sign In Page does not match with the rest of the application. Please refer the below picture for context.

**Describe the solution you'd like**
I want to style the buttons properly as it is in the other pages(same kind of styling) using CSS.
**Describe alternatives you've considered**
There are no alternative solutions as of now.
**Additional context**
<img src = "https://user-images.githubusercontent.com/44313631/133623719-b6d29dbd-3e62-4ea9-8810-1806d0fc359d.PNG" width = 400px height = 400px />

**Comment by vedanthv** [comment]
@A-HK I would like to be assigned to this issue

**Comment by A-HK** [comment]
Sure @vedanthv, will assign this to you as soon as the PR for issue #1 is dealt with

**Comment by vedanthv** [comment]
> Sure @vedanthv, will assign this to you as soon as the PR for issue #1 is dealt with

Thank you

**Comment by vedanthv** [comment]
@A-HK you can assign this issue to @goel-vanshika. I'll work on something else👍

**Comment by A-HK** [comment]
Alrighty.
@goel-vanshika, assigning you here

**Comment by goel-vanshika** [comment]
@vedanthv thanks a lot appreciate it!
@A-HK thank you!

**Comment by A-HK** [comment]
Issue resolved in #19 and #20
