### ISSUE TITLE
Client sign-up+login page authentication with MongoDB

### ISSUE THREAD

**Issue by kruthi3012** [Tech-Matrix/PRNTRS#7]
**Is your feature request related to a problem? Please describe.**
The project currently has a static Client sign-in page. 

**Describe the solution you'd like**
I'd like to integrate it with firebase for the sign-up and login authentication.

**Describe alternatives you've considered**
An alternate to firebase sign-in would be to use Mongo DB (not familiar, but ready to learn if required)

**Comment by kruthi3012** [comment]
@A-HK can you please this to me?

**Comment by A-HK** [comment]
Hey @kruthi3012 , thanks so much for opening this issue !
Would you be willing to learn MongoDB for the client sign up, since the vendor page login's going to be implemented in the same?
I don't really want two backend tools in the same application.

**Comment by A-HK** [comment]
This issue is up for grabs.
If anyone would like to get assigned, please comment below !

**Comment by vedanthv** [comment]
@A-HK I would like to take it up. Raising a fresh issue since I have another good idea. Please close this. Here is the issue #12
