### ISSUE TITLE
Revamp the front-end of mappy.html

### ISSUE THREAD

**Issue by prateekrao** [Tech-Matrix/PRNTRS#8]
**Is your feature request related to a problem? Please describe.**
The front-end design of `mappy.html` looks very clunky and hard to use.

**Describe the solution you'd like**
A complete redoing of the front-end part of `mappy.html`.

**Describe alternatives you've considered**

**Additional context**
Screenshot:
<img width="1671" alt="Screen Shot 2021-09-16 at 8 07 37 PM" src="https://user-images.githubusercontent.com/73730958/133632055-8dc669ad-9167-4de5-8c90-26eade9d9bc8.png">

**Comment by prateekrao** [comment]
@A-HK I'd like to be assigned to this issue!

**Comment by A-HK** [comment]
Awesome ! Have assigned you @prateekrao
