### ISSUE TITLE
[BUG] UI isn't responsive on smaller width screens

### ISSUE THREAD

**Issue by achyuta116** [Tech-Matrix/PRNTRS#9]
**Describe the bug**
UI in the Vendor's Orders List isn't responsive and the elements stack on top of eachother

**To Reproduce**
1. Load the webpage in the browser
2. Resize the browser to see the changes

**Expected behavior**
UI should have been responsive and cleanly displayed on smaller width screens

**Screenshots**

**Desktop (please complete the following information):**
 - Browser :- Brave
 - Version :- 1.18.78

**Comment by A-HK** [comment]
Cool ! Assigning this to you @achyuta116

**Comment by vedanthv** [comment]
@achyuta116 Ping me when you are done with frontend using HTML/CSS. I ll work on the database!

**Comment by achyuta116** [comment]
Will do.
